-- ============================================================
-- Ford Catálogos — DDL Oracle 12c+ (idempotente via PL/SQL)
-- Cada bloco ignora ORA-00955 (objeto já existe) com segurança.
-- ============================================================

-- 1. USUARIOS
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE USUARIOS (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL         VARCHAR2(200)  NOT NULL,
    SENHA_HASH    VARCHAR2(200)  NOT NULL,
    NOME          VARCHAR2(200),
    ROLE          VARCHAR2(20)   DEFAULT ''viewer'' NOT NULL,
    ATIVO         NUMBER(1)      DEFAULT 1 NOT NULL,
    DATA_CRIACAO  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ULTIMO_ACESSO TIMESTAMP,
    CONSTRAINT uq_usuario_email UNIQUE (EMAIL),
    CONSTRAINT ck_usuario_role  CHECK (ROLE IN (''admin'',''analista'',''viewer'')),
    CONSTRAINT ck_usuario_ativo CHECK (ATIVO IN (0,1))
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. CATALOGOS
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CATALOGOS (
    ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MARCA              VARCHAR2(50)    NOT NULL,
    MODELO             VARCHAR2(100)   NOT NULL,
    VERSAO             VARCHAR2(100)   NOT NULL,
    ANO_MODELO         NUMBER(4)       NOT NULL,
    SEGMENTO           VARCHAR2(20)    NOT NULL,
    STATUS             VARCHAR2(30)    NOT NULL,
    COBERTURA_PCT      NUMBER(5,2),
    COBERTURA_LIVE_PCT NUMBER(5,2),
    FONTES_UTILIZADAS  VARCHAR2(2000),
    DATA_EXTRACAO      TIMESTAMP       NOT NULL,
    DATA_CRIACAO       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_catalogo_veiculo UNIQUE (MARCA, MODELO, VERSAO, ANO_MODELO),
    CONSTRAINT ck_catalogo_marca   CHECK (MARCA IN (''ford'',''toyota'',''vw'',''chevrolet'',''mitsubishi'',''nissan'')),
    CONSTRAINT ck_catalogo_status  CHECK (STATUS IN (''completo'',''parcial'',''pendente_revisao'')),
    CONSTRAINT ck_catalogo_segmento CHECK (SEGMENTO IN (''pickup'',''suv''))
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. CATALOGO_ATRIBUTOS
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CATALOGO_ATRIBUTOS (
    ID                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATALOGO_ID          NUMBER         NOT NULL,
    ATRIBUTO             VARCHAR2(100)  NOT NULL,
    VALOR_TEXT           VARCHAR2(4000),
    VALOR_NUMBER         NUMBER,
    TIPO_VALOR           VARCHAR2(20)   NOT NULL,
    CONFIANCA            NUMBER(3,2)    NOT NULL,
    FONTE_PRIMARIA       VARCHAR2(1000),
    MERCADO_CONFIRMADO_BR NUMBER(1)     DEFAULT 1 NOT NULL,
    DIVERGENTE           NUMBER(1)      DEFAULT 0 NOT NULL,
    REVISADO_HUMANO      NUMBER(1)      DEFAULT 0 NOT NULL,
    SCHEMA_NIVEL         VARCHAR2(20)   DEFAULT ''core'' NOT NULL,
    CONSTRAINT fk_atr_catalogo   FOREIGN KEY (CATALOGO_ID) REFERENCES CATALOGOS(ID) ON DELETE CASCADE,
    CONSTRAINT uq_atr_catalogo   UNIQUE (CATALOGO_ID, ATRIBUTO),
    CONSTRAINT ck_atr_tipo_valor CHECK (TIPO_VALOR IN (''text'',''number'',''boolean'',''null'')),
    CONSTRAINT ck_atr_schema_nivel CHECK (SCHEMA_NIVEL IN (''core'',''estendido'')),
    CONSTRAINT ck_atr_confianca  CHECK (CONFIANCA BETWEEN 0 AND 1),
    CONSTRAINT ck_atr_divergente CHECK (DIVERGENTE IN (0,1)),
    CONSTRAINT ck_atr_revisado   CHECK (REVISADO_HUMANO IN (0,1)),
    CONSTRAINT ck_atr_mercado_br CHECK (MERCADO_CONFIRMADO_BR IN (0,1))
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4. CATALOGO_FONTES_SECUNDARIAS
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CATALOGO_FONTES_SECUNDARIAS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATRIBUTO_ID NUMBER        NOT NULL,
    URL         VARCHAR2(1000),
    VALOR_TEXT  VARCHAR2(4000),
    STATUS      VARCHAR2(20)  NOT NULL,
    CONFIANCA   NUMBER(3,2),
    CONSTRAINT fk_fonte_atributo FOREIGN KEY (ATRIBUTO_ID) REFERENCES CATALOGO_ATRIBUTOS(ID) ON DELETE CASCADE,
    CONSTRAINT ck_fonte_status   CHECK (STATUS IN (''confirma'',''diverge'',''complementa'')),
    CONSTRAINT ck_fonte_conf     CHECK (CONFIANCA IS NULL OR CONFIANCA BETWEEN 0 AND 1)
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 5. CAPABILITY_SCORES
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CAPABILITY_SCORES (
    ID                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATALOGO_ID          NUMBER         NOT NULL,
    CAPABILITY           VARCHAR2(100)  NOT NULL,
    NIVEL                NUMBER(2)      NOT NULL,
    NIVEL_MAXIMO_CLUSTER NUMBER(2),
    SCORE_BRUTO          NUMBER(5,2),
    SCORE_AJUSTADO       NUMBER(5,2),
    LIDER_MARCA          VARCHAR2(50),
    DATA_CALCULO         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_cap_catalogo FOREIGN KEY (CATALOGO_ID) REFERENCES CATALOGOS(ID) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 6. SCORE_COMPETITIVO
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE SCORE_COMPETITIVO (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATALOGO_ID       NUMBER        NOT NULL,
    SCORE_TECNICO     NUMBER(5,2),
    SCORE_VALOR       NUMBER(5,2),
    PERFIL_COMPETICAO VARCHAR2(50),
    CLUSTER_IDS       VARCHAR2(500),
    DATA_CALCULO      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_score_catalogo FOREIGN KEY (CATALOGO_ID) REFERENCES CATALOGOS(ID) ON DELETE CASCADE
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 7. CHAT_CACHE
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CHAT_CACHE (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERGUNTA_HASH    VARCHAR2(64)   NOT NULL,
    PERGUNTA_ORIGINAL CLOB          NOT NULL,
    RESPOSTA         CLOB           NOT NULL,
    FONTES_CITADAS   VARCHAR2(2000),
    DATA_CRIACAO     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_EXPIRACAO   TIMESTAMP      NOT NULL,
    CONSTRAINT uq_cache_hash UNIQUE (PERGUNTA_HASH),
    CONSTRAINT ck_cache_exp  CHECK (DATA_EXPIRACAO > DATA_CRIACAO)
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 8. TERMOS_PENDENTES
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE TERMOS_PENDENTES (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TERMO             VARCHAR2(200)  NOT NULL,
    CONTEXTO          VARCHAR2(2000),
    ATRIBUTO_SUGERIDO VARCHAR2(100),
    FONTE             VARCHAR2(1000),
    DATA_DETECTADO    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT ''pendente'' NOT NULL,
    REVISADO_POR      VARCHAR2(100),
    DATA_REVISAO      TIMESTAMP,
    CONSTRAINT ck_termo_status CHECK (STATUS IN (''pendente'',''mapeado'',''descartado''))
  )';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
