-- ============================================================
-- Ford Catálogos — Índices Oracle (idempotente via PL/SQL)
-- Cada bloco ignora ORA-00955 (objeto já existe) e
-- ORA-01408 (coluna já indexada por constraint UNIQUE).
-- ============================================================

-- CATALOGOS
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cat_marca_modelo_versao ON CATALOGOS (MARCA, MODELO, VERSAO)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cat_status ON CATALOGOS (STATUS)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cat_data_extracao ON CATALOGOS (DATA_EXTRACAO)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- CATALOGO_ATRIBUTOS
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_atr_catalogo_id ON CATALOGO_ATRIBUTOS (CATALOGO_ID)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_atr_atributo ON CATALOGO_ATRIBUTOS (ATRIBUTO)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_atr_divergente ON CATALOGO_ATRIBUTOS (DIVERGENTE)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- CATALOGO_FONTES_SECUNDARIAS
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_fonte_atributo_id ON CATALOGO_FONTES_SECUNDARIAS (ATRIBUTO_ID)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- CAPABILITY_SCORES
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cap_catalogo_id ON CAPABILITY_SCORES (CATALOGO_ID)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cap_capability ON CAPABILITY_SCORES (CAPABILITY)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- SCORE_COMPETITIVO
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_score_catalogo_id ON SCORE_COMPETITIVO (CATALOGO_ID)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- CHAT_CACHE
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cache_hash ON CHAT_CACHE (PERGUNTA_HASH)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_cache_expiracao ON CHAT_CACHE (DATA_EXPIRACAO)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- TERMOS_PENDENTES
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_termo_status ON TERMOS_PENDENTES (STATUS)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_termo_data ON TERMOS_PENDENTES (DATA_DETECTADO)';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
