-- Perfil de competição em CAPABILITY_SCORES (evita sobrescrever scores entre perfis)
ALTER TABLE CAPABILITY_SCORES ADD PERFIL_COMPETICAO VARCHAR2(50);

UPDATE CAPABILITY_SCORES SET PERFIL_COMPETICAO = 'desconhecido' WHERE PERFIL_COMPETICAO IS NULL;

CREATE INDEX IDX_CAP_CATALOGO_PERFIL ON CAPABILITY_SCORES (CATALOGO_ID, PERFIL_COMPETICAO);
